### ISSUE TITLE
[1.15.2] Incompatibility with Optifine

### ISSUE THREAD

**Issue by valknight** [TerraformersMC/Traverse#17]
Version of Traverse: 2.1.11
Optifine version: 1.15.2_HD_U_G1_pre9
Optifabric: 0.7.1

Platform: popOS 19.10 using `amdgpu`

Game fails to launch - this seems to be due to an incompatibility between Traverse & Optifabric, with all my other mods working fine on this prerelease. I understand I am using a prerelease build, so, if this is optifine's problem to sort, please shout and I'll make a relevant report over there. My reason for reporting here is the following bit of the error log, which seems to be Traverse specific

```
Suppressed: java.lang.ExceptionInInitializerError
		at com.terraformersmc.traverse.client.TraverseClient.registerTextures(TraverseClient.java:36)
		at com.terraformersmc.traverse.client.TraverseClient.onInitializeClient(TraverseClient.java:20)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
		... 19 more
	Caused by: java.lang.NullPointerException
		at net.optifine.Config.isRandomEntities(Config.java:1861)
		at net.minecraft.class_1921.method_24293(class_1921.java:138)
		at net.minecraft.class_1921.method_23578(class_1921.java:155)
		at net.minecraft.class_4722.<clinit>(class_4722.java:32)
		... 22 more
```

Attached is my log from MultiMC.

[crash-log.txt](https://github.com/TerraformersMC/Traverse/files/4307131/crash-log.txt)

**Comment by Prospector** [comment]
Nothing I can do about an OptiFine incompatibility

**Comment by coderbot16** [comment]
The [latest version of OptiFabric](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/2914099) resolves the issue.

Thanks, modmuss50!
