### ISSUE TITLE
Compatibility issue with Simplex Terrain Generation

### ISSUE THREAD

**Issue by TrueCP6** [TerraformersMC/Traverse#46]
If the weight of any of the `variant` biomes in the Traverse config file is set to 0 or they are disabled, Simplex crashes when attempting to generate the world. This problem does not occur with default terrain generation. I am unsure if this is a problem with Simplex or Traverse so I have posted [this issue to both repos](https://github.com/SuperCoder7979/simplexterrain/issues/34).

Here is the crash report:
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 11/24/20 3:11 PM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3898.method_17225(class_3898.java:579)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	... 12 more
Caused by: java.lang.IllegalStateException: Unknown biome id emitted by layers: 193
	at net.minecraft.class_3642.method_16341(class_3642.java:26)
	at supercoder79.simplexterrain.world.gen.SimplexBiomeSource.getBiomeAt(SimplexBiomeSource.java:73)
	at supercoder79.simplexterrain.world.gen.SimplexBiomeSource.method_16359(SimplexBiomeSource.java:66)
	at net.minecraft.class_1966.method_24385(class_1966.java:119)
	at net.minecraft.class_1966.method_8762(class_1966.java:83)
	at net.minecraft.class_2794.method_28509(class_2794.java:111)
	at net.minecraft.class_2794.method_28507(class_2794.java:334)
	at net.minecraft.class_3188.method_28654(class_3188.java:31)
	at net.minecraft.class_3188.method_14026(class_3188.java:19)
	at net.minecraft.class_3195.method_28657(class_3195.java:259)
	at net.minecraft.class_5312.method_28622(class_5312.java:35)
	at net.minecraft.class_2794.method_28508(class_2794.java:278)
	at net.minecraft.class_2794.method_16129(class_2794.java:264)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 734298928 bytes (700 MB) / 1821376512 bytes (1737 MB) up to 3787980800 bytes (3612 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		adapaxels: AdaPaxels 1.0.4
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.13+MC1.16.2-1.16.4
		baila: baila 1.1.0
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		blast: BLAST 1.4
		cavebiomes: Cave Biomes 0.5.1
		charm: Charm 2.1.1
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftycuisine: Crafty Cuisine b1.1
		crookedcrooks: Crooked Crooks 1.3.2+1.16.4
		fabric: Fabric API 0.26.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ba858fb83a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+6a2618f53a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+6a2618f53a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fatxporbs: Fat Experience Orbs 0.0.7
		flan: Flan 1.16.2-1.1.5
		flesh2leather: Flesh2Leather 1.0.1
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		jankson: Jankson 3.0.1+j1.2.0
		lapisreserve: Lapis Reserve 1.0.6
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.1+1.16.3
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		magna: Magna 1.4.2-1.16.2
		mcdict: MCDict 2.0.0+1.16.4
		mcdw: MC Dungeons Weapons 1.1.8
		minecraft: Minecraft 1.16.4
		org_yaml_snakeyaml: snakeyaml 1.25
		phosphor: Phosphor 0.6.0+build.7
		polymc: PolyMc 2.3.0+1.16.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.4-1.7.0
		simplexterrain: Simplex Terrain 0.7.1
		staffofbuilding: Staff of Building 1.2.3-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.0+build.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		traverse: Traverse 3.0.3+build.13
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		voyager: Voyager 1.0.0
		world_blender: World Blender 1.16.4-1.0.9
	Player Count: 0 / 20; []
	Data Packs: vanilla, fabric/adapaxels, fabric/automated_crafting, fabric/blast, fabric/cavebiomes, fabric/charm, fabric/craftycuisine, fabric/crookedcrooks, fabric/fabric-tool-attribute-api-v1, fabric/flesh2leather, fabric/flora-doubling, fabric/libcd, fabric/mcdw, fabric/repurposed_structures, fabric/staffofbuilding, fabric/traverse, fabric/vanilla-hammers, fabric/world_blender
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by coderbot16** [comment]
I've diagnosed the issue and it appears that this is an issue in Simplex Terrain, so I'm going to close this issue in favor of https://github.com/SuperCoder7979/simplexterrain/issues/34.
