### ISSUE TITLE
Crash when launching the game on Quilt 1.19.3

### ISSUE THREAD

**Issue by RoonMoonlight** [TerraformersMC/Traverse#95]
Crash report is attached below.

When I launch the game, the game crashes. And it says `java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'terraform-wood-api-v1'!`. Most likely related with Terraform API that mod uses.

I am using 1.19.3 with Quilt mod loader, Quilt Standard Libraries and Quilt Kotlin Libraries.
[crash-2023-01-07_23.37.07-client.txt](https://github.com/TerraformersMC/Traverse/files/10366546/crash-2023-01-07_23.37.07-client.txt)

If you need full log, I will post it too

**Comment by gniftygnome** [comment]
I know I've seen this `quilt:tracked_data_handlers` bug before so somebody must have already reported it (probably for Terrestria and likely just in chat).  Quilt is doing something screwy and I'm generally inclined to think they'll have to change it on their end.  We do not officially support Quilt for our biome mods yet because Quilt is not stable enough at this time.  If we found a way to resolve this one you'd likely just run into the Terraform wood API conflict or the Balm crash...

```java
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[quilt:tracked_data_handlers / minecraft:unknown_handler/0] at different raw IDs (2, 24)! If you're trying to override an item, use .set(), not .register()!
        at net.minecraft.class_2370.handler$bpn000$setPre(class_2370.java:706)
        at net.minecraft.class_2370.method_46744(class_2370.java)
        at net.minecraft.class_2370.method_10272(class_2370.java:186)
        at net.minecraft.class_2378.method_39197(class_2378.java:118)
        at net.minecraft.class_2378.method_10230(class_2378.java:114)
        at net.minecraft.class_2943.handler$cfi000$quilt$register(class_2943.java:626)
        at net.minecraft.class_2943.method_12720(class_2943.java)
        at com.terraformersmc.terraform.boat.impl.TerraformBoatTrackedData.register(TerraformBoatTrackedData.java:28)
        at com.terraformersmc.terraform.boat.impl.TerraformBoatInitializer.onInitialize(TerraformBoatInitializer.java:36)
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
        ... 16 more
```

**Comment by RoonMoonlight** [comment]
Should I report this to Quilt devs then?

**Comment by gniftygnome** [comment]
You are welcome to try.  I've reported a few things and never received a response so I assume they are busy with other stuff.

**Comment by RoonMoonlight** [comment]
Yeah you're right, the author of the mod is really busy doing things
Any possible way to fix this issue? I don't think Quilt support might be added right now for TerraformerMC mods

**Comment by RoonMoonlight** [comment]
Posted it to Quilt Forum's [Mod Incompatibility Megathread](https://forum.quiltmc.org/t/mod-incompatibility-megathread/261/43) as well.

**Comment by gniftygnome** [comment]
> somebody must have already reported it

Oh there it is.  https://github.com/TerraformersMC/Terraform/issues/71

**Comment by RoonMoonlight** [comment]
Should we close and move on to that issue then?

**Comment by gniftygnome** [comment]
Might as well leave this open so people can find it and not make a new one.

**Comment by OroArmor** [comment]
This will be fixed by QuiltMC/quilt-standard-libraries#253

**Comment by gniftygnome** [comment]
Resolved long ago by the Quilt folks.
